server:
  port: 8443
  ssl:
    #key-store-password: ${keystorepassword}
    key-store-password: tomcat
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      
