server:
  port: 8084
  
security:
  oauth2:
    client:
      clientId: microclient
      clientSecret: secret
    resource:
#      tokenInfoUri: http://localhost:8081/auth/oauth/check_token
#      user-info-uri:  http://localhost:8081/auth/userinfo
      jwt:        key-uri: http://localhost:1234/auth/oauth/token_key
     